# Generated by Django 3.2.15 on 2022-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parent_name', models.CharField(max_length=80)),
                ('teacher_name', models.CharField(max_length=80)),
                ('child_name', models.CharField(max_length=80)),
                ('class_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
