# Generated by Django 3.2.15 on 2022-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher_name',
            field=models.CharField(max_length=80),
        ),
    ]
